services:
  postgres16:
    image: postgres:16.8
    container_name: postgres-16.8-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ee_midd
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      LANG: "en_US.UTF-8"
      TZ: "UTC"   # 設定容器的系統時區為 UTC
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres16.8:/var/lib/postgresql/data

  postgres14:
    image: postgres:14-alpine
    container_name: postgres-14-db
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ee_midd