version: '3.8'

services:
  ee-midd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ee-midd
    ports:
      - "8080:8080"
    environment:
      # 應用程式設定
      - SPRING_APPLICATION_NAME=ee-midd
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
      - SERVER_SERVLET_CONTEXT_PATH=/ee-midd
      - SERVER_PORT=8080
      
      # thymeleaf 設定
      - SPRING_THYMELEAF_CACHE=false
      - SPRING_THYMELEAF_PREFIX=classpath:/templates/
      - SPRING_THYMELEAF_SUFFIX=.html
      
      # PostgreSQL 資料庫連線設定
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ee_midd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      
      # JPA 設定
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      
      # 日誌設定
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_SOGO_EE_MIDD=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG
      - LOGGING_PATTERN_CONSOLE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
      - LOGGING_CHARSET_CONSOLE=UTF-8
      - LOGGING_CHARSET_FILE=UTF-8
      - LOGGING_LEVEL_ORG_HIBERNATE=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=INFO
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE_JDBCTEMPLATE=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE_STATEMENTCREATORUTILS=TRACE
      - LOGGING_FILE_NAME=/app/logs/ee-midd.log
      - LOGGING_LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE=10MB
      - LOGGING_LOGBACK_ROLLINGPOLICY_MAX_HISTORY=5
      
      # SMTP 設定
      - MAIL_SMTP_HOST=${MAIL_SMTP_HOST:-}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH:-}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT:-}
      - MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE:-}
      - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME:-}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD:-}
      - MAIL_SMTP_MAIL_FROM=${MAIL_SMTP_MAIL_FROM:-}
      - MAIL_SMTP_MAIL_TO=${MAIL_SMTP_MAIL_TO:-}
      - MAIL_SMTP_MAIL_SUBJECT=${MAIL_SMTP_MAIL_SUBJECT:-}
      
      # Swagger UI 設定
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - SPRINGDOC_SWAGGER_UI_ENABLED=true
      - SPRINGDOC_API_DOCS_PATH=/api-docs
      
      # Radar API 設定
      - RADAR_API_SERVER_URI=${RADAR_API_SERVER_URI:-https://uat-ehr.sogo.com.tw/DATAHUB}
      - RADAR_API_TOKEN=${RADAR_API_TOKEN:-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVc2VyUHJvZmlsZUtleSI6IjM4ZDYwZmM3LTA4YzItNGNiNC05NjQ0LWE0ODBlMzQ0YmNhYSIsIlVzZXJJZCI6bnVsbCwiQ29tcGFueVNlcmlhbE5vIjpudWxsLCJFeHBpcnlEYXRlIjowLCJVc2VyRGF0YSI6bnVsbCwiU3lzdGVtTG9naW5EYXRhIjp7IkNsaWVudFNDUmVsYXRlVXNlcklEIjoiU09HT0lUIiwiQ29tcGFueUNvZGUiOiJTT0dPIiwiQ29tcGFueVBhcnR5SUQiOjEsIlRlbmFudElEIjoiVDAwMDAwMDAwMSIsIklzU3VwZXJVc2VyIjpmYWxzZX19.4wQNPiDZZUeEkmlGMSCw2KO9hnMW04gG_dSVjqgiqDc}
      
      # JWT 設定
      - JWT_SECRET=${JWT_SECRET:-fdjksa;312kOIJFfdsaASDWE123fdsa9012FDSAfdsa890FDSfdsa90FDSALfd890FDSfds8902FDJSL890fdFDSA890fdaFDSA890fdsaFDSA890fdsaFDSA890fdsFDSA890fdsaFDSA890}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 